[package]
name = "paritydb"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
bit-vec = "0.4.4"
byteorder = "1.1"
error-chain = "0.11"
hex-slice = "0.1.0"
memmap = "0.5.2"
parking_lot = "0.4.8"
tiny-keccak = "1.3"

[dev-dependencies]
tempdir = "0.3.5"
