[package]
name = "benchmarks"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dev-dependencies]
paritydb = { path = "../paritydb" }
rocksdb = "0.8.1"
lmdb-zero = "0.4.1"
tempdir = "0.3.5"
cuckoofilter = "0.3.2"
rand = "0.3.18"
itertools = "0.7.3"
